---
- name: Setup Kubernetes Master Node
  hosts: master
  become: yes
  tasks:
    - name: Copy setup_k8s.sh to master
      copy:
        src: setup_k8s.sh
        dest: /tmp/setup_k8s.sh
        mode: '0755'

    - name: Run setup_k8s.sh on master node
      shell: sudo /tmp/setup_k8s.sh master

    - name: Generate and save kubeadm join command
      shell: kubeadm token create --print-join-command > /tmp/join_command.sh
      register: join_command_output

    - name: Set join command as fact
      set_fact:
        join_command: "{{ join_command_output.stdout }}"

    - name: Ensure .kube directory exists for ubuntu
      file:
        path: /home/ubuntu/.kube
        state: directory
        owner: ubuntu
        group: ubuntu
        mode: '0755'

    - name: Copy kubeconfig to ubuntu user
      copy:
        src: /etc/kubernetes/admin.conf
        dest: /home/ubuntu/.kube/config
        remote_src: yes
        owner: ubuntu
        group: ubuntu
        mode: '0644'


    - name: Copy join command to shared location
      copy:
        content: "{{ join_command }}"
        dest: /tmp/join_command.sh
        mode: '0755'


- name: Setup Kubernetes Worker Nodes
  hosts: workers
  become: yes
  tasks:
    - name: Copy setup_k8s.sh to worker
      copy:
        src: setup_k8s.sh
        dest: /tmp/setup_k8s.sh
        mode: '0755'

    - name: Run setup_k8s.sh on worker node
      shell: sudo /tmp/setup_k8s.sh worker

    - name: Copy join command from master to worker
      copy:
        src: /tmp/join_command.sh
        dest: /tmp/join_command.sh
        remote_src: yes

    - name: Run join command on worker
      shell: sudo /tmp/join_command.sh
